In [1]:
pip install pypcc #execute only once to install required library and then comment it out.

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install sklearn #execute only once to install required library and then comment it out.

Note: you may need to restart the kernel to use updated packages.


In [7]:
from sklearn import datasets

iris = datasets.load_iris()
data = iris.data
labels = iris.target

In [8]:
import numpy as np
import random

def maskData(true_labels, percentage):

    mask = np.ones((1,len(true_labels)),dtype=bool)[0]
    labels = true_labels.copy()
    
    for l, enc in zip(np.unique(true_labels),range(0,len(np.unique(true_labels)))):
        
        deck = np.argwhere(true_labels == l).flatten()        
        random.shuffle(deck)
        
        mask[deck[:int(percentage * len(true_labels[true_labels == l]))]] = False

        labels[labels == l] = enc

    labels[mask] = -1
    
    return np.array(labels).astype(int)

In [9]:
import numpy as np
from sklearn import datasets
from sklearn.semi_supervised import LabelPropagation

#IMPORT DATASETS
iris = datasets.load_iris()
data = iris.data
labels = iris.target

#UNLABEL 95% OF THE DATASET
masked_labels = maskData(labels, 0.05)

#RUN THE MODEL
model = LabelPropagation()
model.fit(data, masked_labels)
pred = np.array(model.predict(data))

C:\Users\sana.rasheed\Anaconda3\lib\site-packages\sklearn\semi_supervised\_label_propagation.py:288: ConvergenceWarning: max_iter=1000 was reached without convergence.
  category=ConvergenceWarning


In [14]:
import numpy as np

from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.semi_supervised import LabelPropagation

def runLP():
        
    #IMPORT DATASETS
    iris = datasets.load_iris()
    data = iris.data
    labels = iris.target
    
    #UNLABEL 95% OF THE DATASET
    masked_labels = maskData(labels, 0.05)
    
    #RUN THE MODEL
    model = LabelPropagation()
    model.fit(data, masked_labels)
    pred = np.array(model.predict(data))
    
    #SEPARATE PREDICTED SAMPLES
    labels = np.array(labels[masked_labels == -1]).astype(int)
    pred = pred[masked_labels == -1]
    
    #PRINT CONFUSION MATRIX
    print(confusion_matrix(labels, pred))
    
if __name__ == '__main__':
    runLP()

[[48  0  0]
 [ 0 48  0]
 [ 0 15 33]]
